/*
 * This source file was generated by the Gradle 'init' task
 */
package tech.trulydigital;

public class App {
    public String getGreeting() {
        return "Print statement and Java Syntax";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
